[package]
name = "bane"
version = "0.0.2"
authors = ["Richard Anaya"]
edition = "2018"
license = "MIT"
description = "a bytecode inspector for web assembly"

[dependencies]
wasmi = "0.4"
parity-wasm = "0.31"
