[package]
name = "bane"
version = "0.0.1"
authors = ["Richard Anaya"]
edition = "2018"
license = "MIT"
description = "a web assembly native programming language"

[dependencies]
wasmi = "0.4"
parity-wasm = "0.31"
